language: python
cache: pip
matrix:
  include:
    - os: linux
      python: "3.4"
      env: UAMQP_ENV=LINUX34
    - os: linux
      python: "3.5"
      env: UAMQP_ENV=LINUX35
    - os: linux
      python: "3.6"
      env: UAMQP_ENV=LINUX36
# command to install dependencies
sudo: required
services:
  - docker
install:
  - pip install -r dev_requirements.txt
  - python ./setup.py build_ext --inplace
  - pip install -e .
script: 
  - pytest
  - python ./setup.py check -r -s
  - pylint --extension-pkg-whitelist=uamqp.c_uamqp uamqp
