language: python
cache: pip
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r dev_requirements.txt
  - python ./setup.py build_ext --inplace
  - pip install -e .
script: 
  - pytest
  - python ./setup.py check -r -s
